# Be sure to restart your server when you modify this file.

Rails.application.configure do
  config.content_security_policy do |policy|
    policy.default_src :self
    policy.font_src    :self, :data
    policy.object_src  :none
    policy.frame_ancestors :none

    # Scripts: Rails asset pipeline (self) + Leaflet, Popper (unpkg) + Bootstrap ESM (jspm)
    # Nonce covers inline scripts generated by javascript_importmap_tags
    policy.script_src :self,
                      "https://unpkg.com",
                      "https://ga.jspm.io"

    # Styles: app CSS (self) + Leaflet CSS (unpkg).
    # unsafe-inline is needed for Bootstrap/Leaflet injected inline styles.
    policy.style_src :self, :unsafe_inline,
                     "https://unpkg.com"

    # Images: app assets, Active Storage blobs, Leaflet marker PNGs (unpkg),
    # and OpenStreetMap tile servers loaded as <img> by Leaflet
    policy.img_src :self, :data, :blob,
                   "https://unpkg.com",
                   "https://*.tile.openstreetmap.org"

    # XHR/fetch/WebSocket: only back to this origin (Turbo, Active Storage direct uploads)
    policy.connect_src :self
  end

  # Attach a per-request nonce to importmap and other inline script tags.
  # javascript_importmap_tags and javascript_include_tag pick this up automatically.
  config.content_security_policy_nonce_generator = ->(request) { request.session.id.to_s }
  config.content_security_policy_nonce_directives = %w[script-src]
end
